CREATE TABLE IF NOT EXISTS loan_states (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name VARCHAR(100) NOT NULL
);

CREATE TABLE loan_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    interest_rate NUMERIC(5,4) NOT NULL,
    automatic_validation BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    type_identification VARCHAR(20) NOT NULL,
    identification VARCHAR(50) NOT NULL,
    base_salary BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount BIGINT NOT NULL,
    term_months INTEGER NOT NULL,
    user_id BIGINT NOT NULL,
    loan_type_id BIGINT NOT NULL,
    loan_state_id BIGINT NOT NULL,
    CONSTRAINT fk_loans_user
    FOREIGN KEY (user_id)
    REFERENCES users (id),
    CONSTRAINT fk_loans_loan_type
    FOREIGN KEY (loan_type_id)
    REFERENCES loan_types (id),
    CONSTRAINT fk_loans_loan_state
    FOREIGN KEY (loan_state_id)
    REFERENCES loan_states (id)
);

CREATE TABLE IF NOT EXISTS payment_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id BIGINT NOT NULL,
    fee_number INTEGER NOT NULL,
    monthly_payment NUMERIC(15,2) NOT NULL,
    interest NUMERIC(15,2) NOT NULL,
    principal_payment NUMERIC(15,2) NOT NULL,
    remaining_balance NUMERIC(15,2) NOT NULL,

    CONSTRAINT fk_payment_plans_loan
    FOREIGN KEY (loan_id)
    REFERENCES loans (id)
);